server:
  port: 8080

spring:
  application:
    name: LOCAL Idempotent Food Dispenser
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/food-dispenser
      database: feed-record