version: "3.6"

services:
  redis:
    image: redis/redis-stack-server:7.2.0-v6
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data
  mongodb:
    image: mongo:8.0.0-rc20
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
volumes:
  redis_data:
  mongodb_data: